### ISSUE TITLE
Error when import of node module 'windows' in electron

### ISSUE THREAD

**Issue by iPk1001101** [PhilipSkinner/windows#9]
I am updating the node module of an application made by somebody else. The module used is 'windows' and the version that was used was 0.0.8. I updated electron to 22 and the node module 'windows' to the latest version 0.1.2.

I am using the module, as it was used before : 
```
const windows = require('windows'); 
var a = windows.registry('/RegistryPath/').SomeValueName.value;
```

And I am getting the error : 

> A JavaScript error occurred in the main process 
> Uncaught Exception: TypeError: Cannot read properties of undefined (reading 'split')
> at Object. (/path/node_modules/windows/lib/runnable.js:9:29)
>  at Module._compile (node:internal/modules/cjs/loader:1141:14)
>  at Module._extensions..js (node:internal/modules/cjs/loader:1196:10) 
> at Module.load (node:internal/modules/cjs/loader:1011:32) 
> at Module._load (node:internal/modules/cjs/loader:846:12)
>  at f._load (node:electron/js2c/asar_bundle:2:13328) 
> at Module.require (node:internal/modules/cjs/loader:1035:19)
>  at require (node:internal/modules/cjs/helpers:102:18)
>  at Object. (/path/node_modules/windows/index.js:4:17)
>  at Module._compile (node:internal/modules/cjs/loader:1141:14)

The error location is at runnable.js:9 :
```
var path = require('path');
var fs = require('fs');


var exists = require('./utility').exists;
var resolve = require('./utility').resolve;


var PATH = process.env.Path.split(';').filter(function(s){ return ~s.indexOf('node') });
```

I tried to read the environnemental variable in Linux and I found that if I modify the code of the module 'windows' to get process.env.PATH.split(';') instead of process.env.Path.split(';') I don't get the same error. The code move forward to the next conditional loop. But the filter of the line discussed here is looking for the string 'node'. In the case of an electron app when it is package there is no node_module folder. So I also hit the same next error when the app is package; which is :

```
//Bugfix taken from @schmittberger
if (!exists(PATH)) {
  if (process.env.NODE_PATH) {
    PATH = process.env.NODE_PATH
  } else {
    throw new Error('No bin-PATH found');
  }
}
```

At this point I am receiving the Error('No bin-PATH found'). I don't have enough experience to know how to fix such an issue. Even if I add the path to my node bin in the environnemental variable of Linux I will hit the same error when the app is package for Windows as there are no folder "node_modules" in the packaged app.

Hoping everybody has a great holiday.

**Comment by SammyShres** [comment]
Anyone have any update on this? I am having a similar problem. I can run this just fine without changing any code in the machine I'm compiling the electron app in but any other machine gives the No bin-PATH found error. I'm checking this on windows machine.

**Comment by chickahoona** [comment]
Ran into the same issue. Wrapping it into a condition so that its only loaded on a windows system prvents this error from being thrown on e.g. a Mac.

```
let windows
if (process.platform === "win32") {
    windows = require("windows");
}

```
